## HW1: The Normal Distribution

### (a) Key characteristics of the Normal distribution

The Normal (Gaussian) distribution is a continuous probability distribution whose graph is a symmetric, bell-shaped curve. Its key characteristics are:

- **Symmetry**: The curve is perfectly symmetric about its center, so the mean, median, and mode are all equal.
- **Bell shape**: Probability density is highest at the center and decreases smoothly toward both tails, which extend infinitely in both directions without ever touching zero (asymptotic tails).
- **Defined by two parameters**: A Normal distribution is fully described by just its mean ($\mu$) and standard deviation ($\sigma$), written $X \sim N(\mu, \sigma^2)$.
- **Total area equals 1**: Like all probability distributions, the total area under the curve equals 1 (100% of outcomes).

**Role of $\mu$ (mean)**: The mean determines the **location** (center) of the distribution on the number line. Changing $\mu$ shifts the entire bell curve left or right without altering its shape.

**Role of $\sigma$ (standard deviation)**: The standard deviation determines the **spread/width** (shape) of the distribution. A small $\sigma$ produces a tall, narrow curve (values tightly clustered around the mean), while a large $\sigma$ produces a short, wide curve (values more spread out). $\sigma$ does not affect the center of the distribution.

### (b) The Empirical Rule (68-95-99.7 rule)

For any Normal distribution, the Empirical Rule states that data falls within a predictable range of standard deviations from the mean:

- Approximately **68%** of observations lie within **1 standard deviation** of the mean: $[\mu - \sigma,\ \mu + \sigma]$
- Approximately **95%** of observations lie within **2 standard deviations** of the mean: $[\mu - 2\sigma,\ \mu + 2\sigma]$
- Approximately **99.7%** of observations lie within **3 standard deviations** of the mean: $[\mu - 3\sigma,\ \mu + 3\sigma]$

This rule gives a quick, practical way to gauge how likely or unusual a given observation is, and it underlies why observations beyond 3 standard deviations are considered rare outliers.

### (c) Probability that inflation is between 1.5 and 6

Given $X \sim N(\mu=3, \sigma=1.5)$, we want $P(1.5 \le X \le 6)$.

Convert each boundary to a Z-score using $Z = \dfrac{X - \mu}{\sigma}$:

$$Z_1 = \frac{1.5 - 3}{1.5} = \frac{-1.5}{1.5} = -1.0$$

$$Z_2 = \frac{6 - 3}{1.5} = \frac{3}{1.5} = 2.0$$

So we need $P(-1.0 \le Z \le 2.0) = \Phi(2.0) - \Phi(-1.0)$, where $\Phi$ is the standard Normal CDF.

Using standard Normal tables: $\Phi(2.0) \approx 0.9772$ and $\Phi(-1.0) \approx 0.1587$.

$$P(-1.0 \le Z \le 2.0) \approx 0.9772 - 0.1587 = 0.8186$$

**So there is approximately an 81.9% probability that the inflation rate in a randomly selected year falls between 1.5% and 6%.** 


In [1]:
from scipy.stats import norm

mu = 3
sigma = 1.5

x1, x2 = 1.5, 6

z1 = (x1 - mu) / sigma
z2 = (x2 - mu) / sigma 

prob = norm.cdf(z2) - norm.cdf(z1)

print(f"Z1 = {z1:.4f}")
print(f"Z2 = {z2:.4f}")
print(f"P({x1} <= X <= {x2}) = P({z1:.2f} <= Z <= {z2:.2f}) = {prob:.4f} ({prob*100:.2f}%)")


Z1 = -1.0000
Z2 = 2.0000
P(1.5 <= X <= 6) = P(-1.00 <= Z <= 2.00) = 0.8186 (81.86%)


## Question 2: Exploring Income Distribution

Household income $X \sim N(\mu=70000, \sigma=18000)$.

### (a) Percentage of households with income between $52,000 and $106,000

Convert boundaries to Z-scores using $Z = \dfrac{X - \mu}{\sigma}$:

$$Z_1 = \frac{52000 - 70000}{18000} = \frac{-18000}{18000} = -1.0$$

$$Z_2 = \frac{106000 - 70000}{18000} = \frac{36000}{18000} = 2.0$$

So we need $P(-1.0 \le Z \le 2.0) = \Phi(2.0) - \Phi(-1.0) \approx 0.9772 - 0.1587 = 0.8186$.

**So approximately 81.9% of households have an income between $52,000 and $106,000.**

### (b) Minimum income to be in the top 5% of earners

The top 5% corresponds to the 95th percentile, whose Z-score is $Z_{0.95} \approx 1.645$.

$$X = \mu + Z \cdot \sigma = 70000 + 1.645 \times 18000 \approx 70000 + 29610 = 99610$$

**A household needs to earn at least approximately $99,610 to be in the top 5% of earners.**

### (c) Maximum income to qualify for the bottom-20% assistance program

The bottom 20% corresponds to the 20th percentile, whose Z-score is $Z_{0.20} \approx -0.8416$.

$$X = \mu + Z \cdot \sigma = 70000 + (-0.8416) \times 18000 \approx 70000 - 15149 = 54851$$

**A household can earn at most approximately $54,851 to qualify for the program.**

Calculations verified numerically below.

mu_income = 70000
sigma_income = 18000

# (a) P(52000 <= X <= 106000)
x1_income, x2_income = 52000, 106000
z1_income = (x1_income - mu_income) / sigma_income
z2_income = (x2_income - mu_income) / sigma_income
prob_income = norm.cdf(z2_income) - norm.cdf(z1_income)

print(f"(a) Z1 = {z1_income:.4f}, Z2 = {z2_income:.4f}")
print(f"(a) P({x1_income} <= X <= {x2_income}) = {prob_income:.4f} ({prob_income*100:.2f}%)")

# (b) Top 5% => 95th percentile
z_top5 = norm.ppf(0.95)
x_top5 = mu_income + z_top5 * sigma_income
print(f"(b) Z(0.95) = {z_top5:.4f}, minimum income for top 5% = ${x_top5:,.2f}")

# (c) Bottom 20% => 20th percentile
z_bottom20 = norm.ppf(0.20)
x_bottom20 = mu_income + z_bottom20 * sigma_income
print(f"(c) Z(0.20) = {z_bottom20:.4f}, maximum income for bottom 20% = ${x_bottom20:,.2f}")
## Question 2: Exploring Income Distribution

Household income $X \sim N(\mu=70000, \sigma=18000)$.

### (a) Percentage of households with income between $52,000 and $106,000

Convert boundaries to Z-scores using $Z = \dfrac{X - \mu}{\sigma}$:

$$Z_1 = \frac{52000 - 70000}{18000} = \frac{-18000}{18000} = -1.0$$

$$Z_2 = \frac{106000 - 70000}{18000} = \frac{36000}{18000} = 2.0$$

So we need $P(-1.0 \le Z \le 2.0) = \Phi(2.0) - \Phi(-1.0) \approx 0.9772 - 0.1587 = 0.8186$.

**So approximately 81.9% of households have an income between $52,000 and $106,000.**

### (b) Minimum income to be in the top 5% of earners

The top 5% corresponds to the 95th percentile, whose Z-score is $Z_{0.95} \approx 1.645$.

$$X = \mu + Z \cdot \sigma = 70000 + 1.645 \times 18000 \approx 70000 + 29610 = 99610$$

**A household needs to earn at least approximately $99,610 to be in the top 5% of earners.**

### (c) Maximum income to qualify for the bottom-20% assistance program

The bottom 20% corresponds to the 20th percentile, whose Z-score is $Z_{0.20} \approx -0.8416$.

$$X = \mu + Z \cdot \sigma = 70000 + (-0.8416) \times 18000 \approx 70000 - 15149 = 54851$$

**A household can earn at most approximately $54,851 to qualify for the program.**

In [4]:
import numpy as np 
from scipy.stats import norm 
mu_income = 70000
sigma_income = 18000

# (a) P(52000 <= X <= 106000)
x1_income, x2_income = 52000, 106000
z1_income = (x1_income - mu_income) / sigma_income
z2_income = (x2_income - mu_income) / sigma_income
prob_income = norm.cdf(z2_income) - norm.cdf(z1_income)

print(f"(a) Z1 = {z1_income:.4f}, Z2 = {z2_income:.4f}")
print(f"(a) P({x1_income} <= X <= {x2_income}) = {prob_income:.4f} ({prob_income*100:.2f}%)")

# (b) Top 5% => 95th percentile
z_top5 = norm.ppf(0.95)
x_top5 = mu_income + z_top5 * sigma_income
print(f"(b) Z(0.95) = {z_top5:.4f}, minimum income for top 5% = ${x_top5:,.2f}")

# (c) Bottom 20% => 20th percentile
z_bottom20 = norm.ppf(0.20)
x_bottom20 = mu_income + z_bottom20 * sigma_income
print(f"(c) Z(0.20) = {z_bottom20:.4f}, maximum income for bottom 20% = ${x_bottom20:,.2f}")


(a) Z1 = -1.0000, Z2 = 2.0000
(a) P(52000 <= X <= 106000) = 0.8186 (81.86%)
(b) Z(0.95) = 1.6449, minimum income for top 5% = $99,607.37
(c) Z(0.20) = -0.8416, maximum income for bottom 20% = $54,850.82
